### PR TITLE
Simplified Option checking by removing the need to equate specific types.

### PR DESCRIPTION
**Pull request by ssanj**

### CODE REVIEW

**Comment by etorreborre** [comment]
This should actually be (note the triple equals)
```scala
 (ValueParse(None) ~ n).description === None
```

Because in case of a failure you will get a message saying what is the value of `Some(...)`.

**Comment by ssanj** [comment]
Good point.

**Comment by ssanj** [comment]
I've fixed up the PR with === as recommended.

**Comment by markhibberd** [comment]
@ssanj If you rebase onto the latest master I will merge.

**Comment by ssanj** [comment]
@markhibberd I have rebased to master.

**Comment by markhibberd** [comment]
@ssanj Thanks. If you want to rebase you other one on top of master now, I will merge it in as well.

**Pull request merged**
