### PR TITLE
Added empty build.sbt to allow intellij to detect this as sbt project.

### PR DESCRIPTION
**Pull request by ssanj**

### CODE REVIEW

**Comment by markhibberd** [comment]
@ssanj Little bit loathe to do this just for intellij. Will merge for now, just to make it easier for you - but can't guarantee someone want come along and delete it if they see the empty file. Is this a known/reported issue with the intellij plugin?

**Comment by ssanj** [comment]
Yeah, it's ugly. I'll check and open an issue if there isn't one. I also toyed with using the sbt IntelliJ plugin but it only generates the older IntelliJ project format which then needs to be upgraded.

**Comment by charleso** [comment]
@ssanj FWIW I just imported pirate in to IntelliJ without this file. I'm using IDEA 14 CE and a fairly recent version of the Scala plugin.

**Comment by ssanj** [comment]
Interesting. 

I'm using: 
Intellij 14.13 CE
build #IC - 141.1010
built on May 12, 2015.
Scala Plugin: 1.5

I can't use File > Open to open the project, but I can do that with any project that has a build.sbt file.

I found this when searching around the Idea issue tracker: https://youtrack.jetbrains.com/issue/SCL-6464

It seems to indicate that this used to be a problem (in 2013/2014) but has been fixed.

I can use the workaround specified in the issue to get it to work: 
File > New > Project from Existing Sources ... > SBT

So I think we should delete the build.sbt file - Sorry for being annoying.

I was thinking of updating the README.md with instructions for intellij but if @charleso can get it to work out of the box, then I might just leave it as is.

**Comment by etorreborre** [comment]
@ssanj I confirm that I also didn't have any issue with recent versions of Intellij and the Scala plugin.

**Comment by ssanj** [comment]
Cool. I'll create a PR to delete build.sbt.

**Pull request merged**
